### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by colindean** [sgreben/tj#2]
I created a Homebrew formula for version 5.0.2 but Homebrew's rules prohibit submission of formulae that are from GitHub projects less than 30 days old.

The formula can be submitted on February 21. I've set a reminder for myself to check the most current version of tj, update the formula, and submit to homebrew-core.

https://github.com/colindean/homebrew-core/commit/8160fe00ad233520d3fd20e365cca020911035d9

**Comment by colindean** [comment]
Updated for 5.0.3

**Comment by colindean** [comment]
Updated for 6.0.0 in https://github.com/colindean/homebrew-core/commit/6155d13351664acfe380cdb72ec881e3a47a6017

**Comment by sgreben** [comment]
Awesome! Many thanks for doing this :)

**Comment by colindean** [comment]
Updated for 6.0.2 https://github.com/colindean/homebrew-core/commit/2214e0752c4d819889b1515f44ac8b4e69f97753

It'll be old enough to submit on Wednesday.
