### ISSUE TITLE
ISO8601 format?

### ISSUE THREAD

**Issue by jlevy** [sgreben/tj#4]
A great idea; been wondering why no one had written a tool like for some time!

One suggestion: It seems [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) is not listed? In general, a good number of engineers believe ISO8601 in Universal timezone is "the [one true format](https://xkcd.com/1179/)" for production timestamps so not having it be easy and obvious to use is a drawback to using a tool. Note you can add subsecond precision in this format too, e.g. `2018-03-26T05:26:50.129Z`.

Thanks again!

**Comment by jlevy** [comment]
See you do have RFC 3339 but that does differ in particular with the non-UTC timezone: https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats

**Comment by colindean** [comment]
How close does RFC 3339 format get to what you want? My understanding is that RFC 3339 is a profile of ISO 8601: that is, RFC 3339 dates are ISO 8601 dates but not vice versa. RFC 3339 is stricter.

    tj --time-format RFC3339 

https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats

**Comment by colindean** [comment]
Sorry, that's what I get for replying by email.

**Comment by sgreben** [comment]
Hey! I just added an ISO8601 option in 7.0.0, as well as defaulting to UTC unless "Local" or a different timezone is explicitly specified. The format string for ISO8601 is actually the same as RFC3339 - since we only _produce_ (not parse) timestamps, and RFC3339 output is valid ISO8601 output, this should be fine.

**Comment by jlevy** [comment]
Cool!
